/**
 * docparse.js — analyse an uploaded "תיק תיעוד" Word document (.docx) and
 * reconstruct the doc-pack `data` object that the rest of the app understands.
 *
 * It also exposes stripToTemplate(), which turns a filled-in pack into a
 * reusable skeleton (template) by removing everything that changes from one
 * project to the next while keeping the structural / boilerplate "topics".
 *
 * The pack `data` schema is the single source of truth defined in docpack.js:
 *   text:    site_name, site_address, site_subtitle, *_org, *_person,
 *            submit_date, update_date, intro_text, network_arch_text
 *   bullets: scope_items[]
 *   tables:  cameras[]   {idx,cabinet,name,model,port,ip,location}
 *            backhauls[] {idx,type,mpn,vendor,location,ip}
 *            switches[]  {idx,name,mpn,vendor,ip}
 *
 * Parsing is intentionally best-effort and forgiving: a .docx authored by hand
 * (not generated by this system) will still yield whatever we can recognise,
 * and everything we cannot map is preserved verbatim in intro_text so nothing
 * is silently lost. The analysis summary tells the admin what was detected.
 *
 * No external XML parser — docx is a ZIP of XML; we unzip with the PizZip
 * dependency already used by docpack.js and walk word/document.xml with
 * focused, non-catastrophic regexes.
 */

const PizZip = require('pizzip');
const https  = require('https');

// ─── Gemini Vision OCR ───────────────────────────────────────────────────────

// Call Gemini 2.0 Flash with an image buffer; returns raw text response.
function _geminiVision(imageBuffer, mimeType, apiKey) {
  const b64 = imageBuffer.toString('base64');
  const body = JSON.stringify({
    contents: [{
      parts: [
        { text: [
          'Look at this image carefully. It may contain a table with security camera, network backhaul, or network switch data (text may be in Hebrew).',
          '',
          'Step 1 — decide the table type:',
          '  • "cameras"   — rows describe cameras/PTZ/NVR. Clues: camera names (CAM 01, מצלמה), IP addresses, location names, cabinet/panel fields.',
          '  • "backhauls" — rows describe wireless/fiber links. Clues: link type (אלחוטי/סיב), vendor, MPN/model, IP.',
          '  • "switches"  — rows describe network switches. Clues: switch names, vendor, model, IP.',
          '  • "unknown"   — any other image (photo, map, logo, chart, text).',
          '',
          'Step 2 — extract all rows (skip header rows) and map each column to the closest field:',
          '  cameras fields:   idx (row number / מס"ד), cabinet (ארון/ריכוז/panel), name (שם מצלמה/camera name), model (דגם/סוג/type), port (פורט/port/חיבור), ip (כתובת IP), location (מיקום/location/position)',
          '  backhauls fields: idx, type (סוג עורק/link type), mpn (מק"ט/model number), vendor (יצרן/supplier), location (מיקום), ip (כתובת IP)',
          '  switches fields:  idx, name (שם מתג), mpn (מק"ט), vendor (יצרן), ip (כתובת IP)',
          '',
          'Step 3 — return ONLY a JSON object, no markdown, no explanation:',
          '{ "type": "cameras", "rows": [ { "idx": "1", "name": "CAM 01", "ip": "10.0.0.1", "location": "כניסה ראשית" }, ... ] }',
          '',
          'Rules:',
          '  - Include every data row (not the header).',
          '  - Use the original Hebrew/English text as-is for field values.',
          '  - If a column has no matching field, skip it.',
          '  - If the image is a photo, plan, or non-table content, return: {"type":"unknown","rows":[]}',
        ].join('\n') },
        { inline_data: { mime_type: mimeType, data: b64 } },
      ],
    }],
    generationConfig: { temperature: 0, maxOutputTokens: 2048 },
  });

  return new Promise((resolve, reject) => {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent?key=${apiKey}`;
    const req = https.request(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) },
    }, res => {
      let raw = '';
      res.on('data', d => raw += d);
      res.on('end', () => {
        try {
          const j = JSON.parse(raw);
          const text = j?.candidates?.[0]?.content?.parts?.[0]?.text || '';
          resolve(text.trim());
        } catch { resolve(''); }
      });
    });
    req.on('error', reject);
    req.setTimeout(30000, () => { req.destroy(new Error('timeout')); });
    req.write(body);
    req.end();
  });
}

// Parse Gemini's JSON response into { type, rows }.
function _parseGeminiResponse(text) {
  const clean = text.replace(/^```[a-z]*\n?/i, '').replace(/\n?```$/,'').trim();
  try {
    const j = JSON.parse(clean);
    if (!j || !Array.isArray(j.rows)) return null;
    return j;
  } catch { return null; }
}

// Extract and OCR all images embedded in the .docx ZIP.
// Returns { cameras:[], backhauls:[], switches:[], imagesProcessed, warnings:[] }
async function extractTablesFromImages(zip, apiKey) {
  const result = { cameras: [], backhauls: [], switches: [], imagesProcessed: 0, warnings: [] };
  if (!apiKey) return result;

  const mediaFiles = Object.keys(zip.files).filter(n =>
    /^word\/media\//i.test(n) && /\.(png|jpe?g|gif|bmp|webp)$/i.test(n)
  );
  if (!mediaFiles.length) return result;

  for (const name of mediaFiles) {
    let buf;
    try { buf = zip.files[name].asNodeBuffer(); } catch { continue; }
    if (!buf || buf.length < 512) continue; // skip tiny icons
    if (buf.length > 8 * 1024 * 1024) {     // skip huge images (>8MB raw)
      result.warnings.push(`תמונה ${name} גדולה מדי לעיבוד, דולגה.`);
      continue;
    }
    const mime = /\.png$/i.test(name) ? 'image/png' : 'image/jpeg';
    let rawText;
    try { rawText = await _geminiVision(buf, mime, apiKey); }
    catch (e) { result.warnings.push(`OCR נכשל עבור ${name}: ${e.message}`); continue; }

    result.imagesProcessed++;
    const parsed = _parseGeminiResponse(rawText);
    if (!parsed || parsed.type === 'unknown' || !parsed.rows.length) continue;
    if (['cameras', 'backhauls', 'switches'].includes(parsed.type)) {
      result[parsed.type].push(...parsed.rows);
    }
  }
  return result;
}

// ─── low-level OOXML text helpers ───────────────────────────────────────────

// Decode the five XML entities that appear in <w:t> runs.
function _xmlDecode(s) {
  return String(s || '')
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"').replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, d) => { try { return String.fromCodePoint(+d); } catch { return ''; } })
    .replace(/&amp;/g, '&'); // ampersand last so &amp;lt; → &lt; isn't double-decoded
}

// Extract the visible text of a <w:p> / <w:tc> fragment.
//
// We must replace soft markers (<w:tab/>, <w:br/>, paragraph ends) FIRST and
// then strip ALL remaining tags — rather than only collecting <w:t> contents.
// A line break inside a paragraph is encoded as <w:br/> sitting *between* two
// <w:t> runs, so a <w:t>-only extractor silently drops it and merges the lines.
// In OOXML the only text nodes live inside <w:t>, so a blanket tag-strip leaves
// exactly the run text plus our inserted markers.
function _fragmentText(xml) {
  if (!xml) return '';
  let s = String(xml);
  s = s.replace(/<w:tab\b[^>]*\/?>/g, ' ');
  s = s.replace(/<w:br\b[^>]*\/?>/g, '\n');
  s = s.replace(/<w:cr\b[^>]*\/?>/g, '\n');
  s = s.replace(/<\/w:p>/g, '\n'); // each inner paragraph (e.g. in a cell) → newline
  s = s.replace(/<[^>]+>/g, '');   // strip every remaining tag
  return _xmlDecode(s)
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n[ \t]+/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

// Is this paragraph a heading? Detect via pStyle (Heading1/כותרת/Title…) or a
// bold-only short line. Returns a rough level number (1 = biggest) or 0.
function _headingLevel(pXml) {
  const styleMatch = pXml.match(/<w:pStyle\b[^>]*w:val="([^"]*)"/i);
  if (styleMatch) {
    const v = styleMatch[1];
    if (/^Title$/i.test(v)) return 1;
    const h = v.match(/Heading\s*(\d)/i) || v.match(/^\s*(\d)\s*כותרת/);
    if (h) return parseInt(h[1], 10) || 2;
    if (/heading|כותרת|title|cover/i.test(v)) return 2;
  }
  return 0;
}

// ─── table parsing ──────────────────────────────────────────────────────────

// Does the byte after an opening "<w:NAME" delimit a real element start
// (">", whitespace, or "/")? Guards against "<w:p" matching "<w:pPr"/"<w:proofErr".
function _isTagBoundary(ch) {
  return ch === '>' || ch === ' ' || ch === '/' || ch === '\t' || ch === '\n' || ch === '\r';
}

// Scan from `i` for the next real "<w:NAME" opening tag (not a longer sibling
// like <w:pPr>). Returns the index or -1.
function _findTag(s, name, i) {
  const needle = '<w:' + name;
  let p = s.indexOf(needle, i);
  while (p >= 0 && !_isTagBoundary(s[p + needle.length])) {
    p = s.indexOf(needle, p + needle.length);
  }
  return p;
}

// Parse a <w:tbl>…</w:tbl> fragment into a 2-D array of trimmed cell strings.
// Linear indexOf scan (no regex backtracking) — safe on malformed input.
function _parseTable(tblXml) {
  const rows = [];
  let i = 0;
  while (i < tblXml.length) {
    const trS = _findTag(tblXml, 'tr', i);
    if (trS < 0) break;
    const trE = tblXml.indexOf('</w:tr>', trS);
    if (trE < 0) break;
    const rowXml = tblXml.slice(trS, trE + 7);
    const cells = [];
    let j = 0;
    while (j < rowXml.length) {
      const tcS = _findTag(rowXml, 'tc', j);
      if (tcS < 0) break;
      const tcE = rowXml.indexOf('</w:tc>', tcS);
      if (tcE < 0) break;
      cells.push(_fragmentText(rowXml.slice(tcS, tcE + 7)));
      j = tcE + 7;
    }
    if (cells.length) rows.push(cells);
    i = trE + 7;
  }
  return rows;
}

// ─── header → field column mapping ──────────────────────────────────────────
// Each table type lists the canonical fields and the header keywords that hint
// at a given column. Matching is normalised (spaces / quotes / punctuation
// stripped) and substring-based so "מס\"ד" matches "מסד" etc.

function _norm(s) {
  return String(s || '').replace(/["'`.,:;()\-_/\\\s]+/g, '').trim();
}

const CAMERA_COLS = [
  { field: 'idx',      hints: ['מסד', 'מספר', '#'] },
  { field: 'cabinet',  hints: ['ארון', 'ארוןתקשורת'] },
  { field: 'name',     hints: ['שםהמצלמה', 'שםמצלמה', 'שם'] },
  { field: 'model',    hints: ['סוגמצלמה', 'דגם', 'מקט', 'דגםמצלמה'] },
  { field: 'port',     hints: ['פורט', 'פנל', 'פורטבפנל'] },
  { field: 'ip',       hints: ['כתובתip', 'ip', 'כתובת'] },
  { field: 'location', hints: ['מיקום', 'מיקוםבתכנית', 'מיקוםבתוכנית'] },
];
const BACKHAUL_COLS = [
  { field: 'idx',      hints: ['מסד', 'מספר', '#'] },
  { field: 'type',     hints: ['סוגעורק', 'סוג', 'עורק'] },
  { field: 'mpn',      hints: ['מקט', 'דגם', 'mpn'] },
  { field: 'vendor',   hints: ['יצרן', 'ספק', 'vendor'] },
  { field: 'location', hints: ['מיקום'] },
  { field: 'ip',       hints: ['כתובתip', 'ip', 'כתובת'] },
];
const SWITCH_COLS = [
  { field: 'idx',    hints: ['מסד', 'מספר', '#'] },
  { field: 'name',   hints: ['מתגים', 'מתג', 'שם'] },
  { field: 'mpn',    hints: ['מקט', 'דגם', 'mpn'] },
  { field: 'vendor', hints: ['יצרן', 'ספק', 'vendor'] },
  { field: 'ip',     hints: ['כתובתip', 'ip', 'כתובת'] },
];

// Map a header row to { columnIndex → field } for a given column spec.
// Returns null when too few columns match (so a non-equipment table is skipped).
function _mapHeader(headerCells, spec) {
  const map = {};
  const used = new Set();
  headerCells.forEach((cell, idx) => {
    const n = _norm(cell);
    if (!n) return;
    // pick the spec entry with the strongest (longest) hint contained in the cell
    let best = null, bestLen = 0;
    for (const col of spec) {
      if (used.has(col.field)) continue;
      for (const h of col.hints) {
        if (n.includes(h) && h.length > bestLen) { best = col.field; bestLen = h.length; }
      }
    }
    if (best) { map[idx] = best; used.add(best); }
  });
  return Object.keys(map).length >= 2 ? map : null;
}

// Score how well a header row fits a spec (used to choose the table's type).
function _headerScore(headerCells, spec) {
  const map = _mapHeader(headerCells, spec);
  return map ? Object.keys(map).length : 0;
}

// Build equipment rows from a table given a header→field map.
function _rowsFromTable(table, headerMap, fields) {
  const out = [];
  for (let r = 1; r < table.length; r++) {
    const cells = table[r];
    const obj = {};
    let any = false;
    for (const [idxStr, field] of Object.entries(headerMap)) {
      const val = (cells[+idxStr] || '').trim();
      if (val) { obj[field] = val; any = true; }
    }
    // Skip the rare repeated-header row and fully empty rows
    if (!any) continue;
    out.push(obj);
  }
  return out;
}

// ─── parties / info table mapping ───────────────────────────────────────────
// A 2- or 3-column "role | function | name" style table on the cover page maps
// to the *_org / *_person contact fields.
const ROLE_TO_KEY = [
  { re: /גורם\s*מבצע|מבצע|קבלן/,            base: 'contractor' },
  { re: /גורם\s*מוביל|מוביל|מנהל\s*פרויקט/, base: 'pm' },
  { re: /לקוח/,                              base: 'customer' },
  { re: /יועץ/,                              base: 'consultant' },
  { re: /מהנדס/,                             base: 'engineer' },
];

function _looksLikeOrg(s) {
  // Company names tend to contain בע"מ / Ltd / inc, or no spaces-with-given-name pattern.
  return /בע["']?מ|בעמ|ltd|inc|בע\"מ|חברה|תעשיות|מערכות|טכנולוג/i.test(s);
}

// ─── main entry: parse a .docx buffer into { data, analysis } ────────────────

async function parseDocxToPackData(buffer, { geminiApiKey } = {}) {
  if (!buffer || !buffer.length) throw new Error('empty file');
  let zip;
  try { zip = new PizZip(buffer); }
  catch (e) { throw new Error('not a valid .docx (zip) file'); }
  const docFile = zip.file('word/document.xml');
  if (!docFile) throw new Error('word/document.xml missing — not a Word document');

  // Guard against zip-bombs / pathological inputs before we materialise or scan
  // the XML. A real "תיק תיעוד" document.xml is well under a couple of MB; 12MB
  // is generous. We check the declared uncompressed size first (cheap) when the
  // zip lib exposes it, then re-check the actual string length.
  const MAX_DOC_XML = 12 * 1024 * 1024;
  const declared = docFile._data && (docFile._data.uncompressedSize || docFile._data.length);
  if (declared && declared > MAX_DOC_XML) throw new Error('המסמך גדול מדי לעיבוד');
  let xml = docFile.asText();
  if (xml.length > MAX_DOC_XML) throw new Error('המסמך גדול מדי לעיבוד');

  // Isolate the body so we don't pick up header/footer parts inadvertently.
  const bodyStart = xml.indexOf('<w:body');
  const bodyEnd = xml.lastIndexOf('</w:body>');
  const body = (bodyStart >= 0 && bodyEnd > bodyStart) ? xml.slice(bodyStart, bodyEnd) : xml;

  // Walk top-level blocks IN ORDER using a linear indexOf scan (NOT a regex with
  // `[\s\S]*?`, which is O(n²) on unclosed tags and event-loop-blockable). At
  // each step we take whichever of the next <w:tbl> / <w:p> starts first; the
  // table branch jumps past the whole table so its nested <w:p> are not matched
  // again. Missing close tags simply end the walk.
  const blocks = [];
  let i = 0, guard = 0;
  while (i < body.length && guard++ < 500000) {
    const tS = _findTag(body, 'tbl', i);
    const pS = _findTag(body, 'p', i);
    if (tS < 0 && pS < 0) break;
    const isTbl = pS < 0 || (tS >= 0 && tS < pS);
    if (isTbl) {
      const e = body.indexOf('</w:tbl>', tS);
      if (e < 0) break;
      blocks.push({ type: 'table', table: _parseTable(body.slice(tS, e + 8)) });
      i = e + 8;
    } else {
      const e = body.indexOf('</w:p>', pS);
      if (e < 0) break;
      const frag = body.slice(pS, e + 6);
      blocks.push({ type: 'p', text: _fragmentText(frag), level: _headingLevel(frag) });
      i = e + 6;
    }
  }

  const data = {};
  const analysis = { sections: [], tables: [], warnings: [], parties: 0, photosNote: '' };

  // ── 1. equipment + info tables ──
  let tablesSeen = 0, tablesUnclassified = 0;
  for (const blk of blocks) {
    if (blk.type !== 'table' || !blk.table.length) continue;
    tablesSeen++;
    const header = blk.table[0] || [];
    const scores = {
      cameras:   _headerScore(header, CAMERA_COLS),
      backhauls: _headerScore(header, BACKHAUL_COLS),
      switches:  _headerScore(header, SWITCH_COLS),
    };
    // backhaul/switch/camera share many hints; disambiguate with strong unique
    // stems so plural / prefixed headers ("רשימת מצלמות", "עורקים") still score.
    const headerNorm = header.map(_norm).join('|');
    if (/עור?ק/.test(headerNorm)) scores.backhauls += 2;
    if (/מתג/.test(headerNorm))   scores.switches  += 2;
    if (/מצלמ/.test(headerNorm))  scores.cameras   += 2;

    const best = Object.entries(scores).sort((a, b) => b[1] - a[1])[0];
    if (best && best[1] >= 3) {
      const type = best[0];
      const spec = type === 'cameras' ? CAMERA_COLS : type === 'backhauls' ? BACKHAUL_COLS : SWITCH_COLS;
      const map = _mapHeader(header, spec);
      const rows = map ? _rowsFromTable(blk.table, map, spec) : [];
      if (rows.length) {
        data[type] = (data[type] || []).concat(rows);
        analysis.tables.push({ type, rows: rows.length });
      }
      // A recognised-but-empty equipment table (header only) is fine — not a
      // warning. Only tables matching NO known shape count as unclassified.
      continue;
    }

    // Otherwise: try the parties / info table (role | … | name).
    let partyHits = 0;
    for (const row of blk.table) {
      const joined = row.join(' ');
      const roleCell = row.find(c => ROLE_TO_KEY.some(rk => rk.re.test(c))) || '';
      if (!roleCell) continue;
      const hit = ROLE_TO_KEY.find(rk => rk.re.test(roleCell));
      if (!hit) continue;
      // value cells = everything except the matched role label
      const values = row.filter(c => c !== roleCell).map(s => s.trim()).filter(Boolean);
      if (!values.length) continue;
      // last cell is usually the person; an org-looking cell fills *_org
      const orgCell = values.find(_looksLikeOrg);
      const personCell = values.filter(v => v !== orgCell).pop() || (orgCell ? '' : values.pop());
      if (orgCell && !data[hit.base + '_org'])       { data[hit.base + '_org'] = orgCell; partyHits++; }
      if (personCell && !data[hit.base + '_person']) { data[hit.base + '_person'] = personCell; partyHits++; }
    }
    if (partyHits) analysis.parties += partyHits;
    else tablesUnclassified++;
  }
  if (tablesUnclassified > 0) {
    analysis.warnings.push(`${tablesUnclassified} מתוך ${tablesSeen} טבלאות לא זוהו אוטומטית — בדוק אותן ידנית.`);
  }

  // ── 2. headings → sections; route following paragraphs ──
  // Content markers OPEN a capture region; anything else that is a heading or a
  // short "label:" line CLOSES the current region so unrelated content (image
  // captions, later section titles) does not bleed into intro / network text.
  const SECTION_MARKERS = [
    { re: /^הקדמה/,                                key: 'intro' },
    { re: /תכולת\s*ה?פרויקט|^תכולה\b/,             key: 'scope' },
    { re: /ארכיטקטור|תיאור\s*ה?רשת\b/,             key: 'network' },
  ];
  const introParas = [];
  const networkParas = [];
  const scopeItems = [];
  let current = null;

  for (const blk of blocks) {
    if (blk.type !== 'p') { if (blk.type === 'table') current = null; continue; }
    const text = (blk.text || '').trim();
    if (!text) continue;

    // A marker only counts on a heading-like line — a styled heading, or a
    // short label with no sentence punctuation. This stops a body sentence that
    // merely *starts* with a section word (e.g. "הקדמה כללית לפרויקט…") from
    // being mistaken for the section heading itself.
    const headingish = blk.level > 0 || (text.length < 18 && !/[.!?:：]$/.test(text));
    const marker = headingish ? SECTION_MARKERS.find(s => s.re.test(text)) : null;
    if (marker) {
      current = marker.key;
      if (!analysis.sections.includes(text)) analysis.sections.push(text);
      continue;
    }
    // Any other heading, or a short "label:" line, closes the current region.
    const isBoundary = (blk.level > 0) || (/[:：]\s*$/.test(text) && text.length < 30);
    if (isBoundary) {
      if (blk.level > 0 && !analysis.sections.includes(text)) analysis.sections.push(text);
      current = null;
      continue;
    }
    if (current === 'intro')        introParas.push(text);
    else if (current === 'network') networkParas.push(text);
    else if (current === 'scope') {
      // each line is a bullet; strip a leading glyph or "N." / "N)" numbering
      // marker only — never a bare number that is part of the content.
      text.split('\n')
        .map(s => s.replace(/^\s*(?:[•·▪◦‣–—\-\*]\s+|\d+[.)]\s+)/, '').trim())
        .filter(Boolean)
        .forEach(b => scopeItems.push(b));
    }
  }

  if (introParas.length)   data.intro_text = introParas.join('\n\n');
  if (networkParas.length) data.network_arch_text = networkParas.join('\n\n');
  if (scopeItems.length)   data.scope_items = scopeItems;

  // ── 3. site name / address (cover heuristic + explicit labels) ──
  // Priority 1: explicit "שם האתר:" / "כתובת:" label paragraphs anywhere.
  const labelled = blocks.find(b => b.type === 'p' && /שם\s*האתר\s*[:：]/.test(b.text || ''));
  if (labelled) data.site_name = labelled.text.replace(/[\s\S]*שם\s*האתר\s*[:：]\s*/, '').trim();
  const addrPara = blocks.find(b => b.type === 'p' && /^\s*כתובת\s*[:：]/.test(b.text || ''));
  if (addrPara) data.site_address = addrPara.text.replace(/[\s\S]*?כתובת\s*[:：]\s*/, '').trim();

  // Priority 2: cover layout — the site name & address are the last short,
  // non-boilerplate paragraphs that appear BEFORE the first table / heading.
  if (!data.site_name) {
    const cover = [];
    for (const blk of blocks) {
      if (blk.type === 'table') break;
      if (blk.level > 0) break;                 // reached the first real heading
      const t = (blk.text || '').trim();
      if (!t || t.length > 60) continue;
      if (/^תיק\s*תיעוד$/.test(t) || /^as[-\s]?made$/i.test(t)) continue; // doc-type labels
      cover.push(t);
      if (cover.length > 6) break;              // never scan deep into the body
    }
    if (cover.length) {
      const last = cover[cover.length - 1];
      const addrLike = /\d|רחוב|שדרות|שד'|דרך|כביש|ת\.?ד|מיקוד|קומה/.test(last);
      if (cover.length >= 2 && addrLike) {
        data.site_name = cover[cover.length - 2];
        if (!data.site_address) data.site_address = last;
      } else {
        data.site_name = last;
      }
    }
  }

  // ── 4. preserve anything unrecognised so nothing is lost ──
  // (Only when we recognised very little — avoid dumping a whole doc when the
  //  structured extraction already worked.)
  const recognised = !!(data.cameras || data.backhauls || data.switches ||
                        data.intro_text || data.scope_items);
  if (!recognised) {
    const allText = blocks.filter(b => b.type === 'p' && b.text).map(b => b.text).join('\n\n').slice(0, 8000);
    if (allText) {
      data.intro_text = allText;
      analysis.warnings.push('לא זוהה מבנה מוכר — הטקסט נשמר בשדה ההקדמה לעיון.');
    }
  }

  // ── 5. OCR images with Gemini Vision (if API key available) ──
  const mediaFiles = Object.keys(zip.files).filter(n => /^word\/media\//i.test(n));
  const imageFiles = mediaFiles.filter(n => /\.(png|jpe?g|gif|bmp|webp)$/i.test(n));
  if (imageFiles.length && geminiApiKey) {
    try {
      const ocr = await extractTablesFromImages(zip, geminiApiKey);
      for (const tbl of ['cameras', 'backhauls', 'switches']) {
        if (ocr[tbl] && ocr[tbl].length) {
          data[tbl] = [...(data[tbl] || []), ...ocr[tbl]];
          const existing = analysis.tables.find(t => t.type === tbl);
          if (existing) existing.rows += ocr[tbl].length;
          else analysis.tables.push({ type: tbl, rows: ocr[tbl].length, fromImage: true });
        }
      }
      if (ocr.imagesProcessed) {
        analysis.photosNote = `עובדו ${ocr.imagesProcessed} תמונות ב-OCR — ${
          ocr.cameras.length + ocr.backhauls.length + ocr.switches.length
        } שורות ציוד נמצאו בתמונות.`;
      }
      if (ocr.warnings.length) analysis.warnings.push(...ocr.warnings);
    } catch (e) {
      analysis.warnings.push('OCR תמונות נכשל: ' + e.message);
    }
  } else if (imageFiles.length) {
    analysis.photosNote = `המסמך כלל ${imageFiles.length} תמונות מוטמעות — יש להעלות אותן מחדש ידנית.`;
  }

  analysis.fields = Object.keys(data).filter(k => !Array.isArray(data[k]) && data[k]).length;
  return { data, analysis };
}

// ─── stripToTemplate ─────────────────────────────────────────────────────────
// Turn a filled pack into a reusable skeleton: drop everything project-specific,
// keep the structural / boilerplate "topics" so a new project starts pre-shaped.

// Per-project values we always clear:
const VARIABLE_TEXT_FIELDS = [
  'site_name', 'site_address', 'site_subtitle',
  'submit_date', 'update_date',
  'contractor_org', 'contractor_person',
  'pm_org', 'pm_person',
  'customer_org', 'customer_person',
  'consultant_org', 'consultant_person',
  'engineer_org', 'engineer_person',
];
// Within equipment rows, blank the instance-specific cells but KEEP the
// reusable equipment identity (model / type / vendor / mpn) — similar sites
// usually deploy the same gear, just at different IPs / locations.
const ROW_INSTANCE_FIELDS = ['idx', 'ip', 'port', 'location', 'cabinet', 'name'];

function stripToTemplate(data) {
  const src = (data && typeof data === 'object') ? data : {};
  const out = JSON.parse(JSON.stringify(src));
  for (const f of VARIABLE_TEXT_FIELDS) delete out[f];
  for (const tbl of ['cameras', 'backhauls', 'switches']) {
    if (!Array.isArray(out[tbl])) continue;
    out[tbl] = out[tbl].map(row => {
      const r = { ...row };
      for (const f of ROW_INSTANCE_FIELDS) delete r[f];
      return r;
    }).filter(r => Object.values(r).some(v => String(v || '').trim())); // drop now-empty rows
  }
  // intro_text / network_arch_text / scope_items are kept as boilerplate.
  return out;
}

module.exports = { parseDocxToPackData, stripToTemplate };
